# Generated by Django 5.1.4 on 2025-07-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_Season', models.CharField(default='summer', max_length=500, verbose_name='Время года')),
                ('event_Text', models.CharField(max_length=500, verbose_name='Текст события')),
                ('action_1', models.CharField(max_length=500, verbose_name='Действие 1')),
                ('consequence_1', models.CharField(max_length=500, verbose_name='Последствие 1')),
                ('received_HP', models.IntegerField(default=0, verbose_name='Изменение здоровья 1')),
                ('received_Money', models.IntegerField(default=0, verbose_name='Изменение монет 1')),
                ('received_Loyalty', models.IntegerField(default=0, verbose_name='Изменение лояльности 1')),
                ('image_Event', models.ImageField(blank=True, max_length=10000, null=True, upload_to='image/event', verbose_name='Изображение события')),
                ('received_Medicinal_herbs', models.IntegerField(default=0, verbose_name='Лечебные травы')),
                ('action_2', models.CharField(max_length=500, verbose_name='Действие 2')),
                ('consequence_2', models.CharField(max_length=500, verbose_name='Последствие 2')),
                ('received_HP_2', models.IntegerField(default=0, verbose_name='Изменение здоровье 2')),
                ('received_Money_2', models.IntegerField(default=0, verbose_name='Изменение монет 2')),
                ('received_Loyalty_2', models.IntegerField(default=0, verbose_name='Изменение лояльности 2')),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_HP', models.IntegerField(blank=True, default=100, null=True)),
                ('status_Money', models.IntegerField(blank=True, default=50, null=True)),
                ('status_Loyalty', models.IntegerField(blank=True, default=0, null=True)),
                ('status_Herbs', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'statuses',
            },
        ),
    ]
