# Generated by Django 5.1.4 on 2025-07-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_restart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='received_Samogon',
            field=models.IntegerField(default=0, verbose_name='Самогон'),
        ),
    ]
