# Generated by Django 5.1.4 on 2025-07-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_restart', '0003_event_received_poison'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_Poison',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='status_Samogon',
            field=models.IntegerField(default=0),
        ),
    ]
