# Generated by Django 5.1.4 on 2025-07-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_restart', '0004_status_status_poison_status_status_samogon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_Money',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_Poison',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_Samogon',
            field=models.IntegerField(default=3),
        ),
    ]
