# Generated by Django 5.1.4 on 2025-07-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_restart', '0005_alter_status_status_money_alter_status_status_poison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='received_Fish',
            field=models.IntegerField(default=0, verbose_name='Рыба'),
        ),
        migrations.AddField(
            model_name='status',
            name='status_Fish',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_Money',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_Poison',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_Samogon',
            field=models.IntegerField(default=0),
        ),
    ]
