# Generated by Django 5.1.4 on 2025-08-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play_restart', '0008_status_status_jewelry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='event',
        ),
        migrations.DeleteModel(
            name='status',
        ),
    ]
