# Generated by Django 5.1.4 on 2025-09-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='health_change',
        ),
    ]
