# Generated by Django 5.1.4 on 2025-09-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_remove_scene_health_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='required_items',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scene',
            name='required_items',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='choice',
            name='required_flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='scene',
            name='required_flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='scene',
            name='set_flags',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
