# Generated by Django 5.1.4 on 2025-09-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_choice_required_items_scene_required_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='received_items_choise',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scene',
            name='received_items',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
