# Generated by Django 5.1.4 on 2025-09-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0004_choice_received_items_choise_scene_received_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='description_stop',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
