# Generated by Django 5.1.4 on 2025-09-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0006_scene_description_stop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='description_stop',
        ),
    ]
