# Generated by Django 5.1.4 on 2025-09-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0007_remove_scene_description_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='description_stop',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
