# Generated by Django 5.1.4 on 2025-09-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0008_scene_description_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='death_redirect',
            field=models.BooleanField(default=False),
        ),
    ]
