# Generated by Django 5.1.4 on 2025-03-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_Text', models.CharField(max_length=500)),
                ('action_1', models.CharField(max_length=500)),
                ('consequence_1', models.CharField(max_length=500)),
                ('received_HP', models.IntegerField()),
                ('received_Money', models.IntegerField()),
                ('received_Loyalty', models.IntegerField()),
                ('lost_HP', models.IntegerField()),
                ('lost_Money', models.IntegerField()),
                ('lost_Loyalty', models.IntegerField()),
                ('action_2', models.CharField(max_length=500)),
                ('consequence_2', models.CharField(max_length=500)),
                ('received_HP_2', models.IntegerField()),
                ('received_Money_2', models.IntegerField()),
                ('received_Loyalty_2', models.IntegerField()),
                ('lost_HP_2', models.IntegerField()),
                ('lost_Money_2', models.IntegerField()),
                ('lost_Loyalty_2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_HP', models.IntegerField(blank=True, null=True)),
                ('status_Money', models.IntegerField(blank=True, null=True)),
                ('status_Loyalty', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
