# Generated by Django 5.1.4 on 2025-03-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_Event',
            field=models.ImageField(blank=True, height_field=1000, max_length=1000, null=True, upload_to='play/templates/image/event/%Y/%m/%d', width_field=1000),
        ),
    ]
