# Generated by Django 5.1.4 on 2025-03-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_event_image_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_Consequence_1',
            field=models.ImageField(blank=True, height_field=1000, max_length=1000, null=True, upload_to='play/templates/image/consequence_1', width_field=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='image_Consequence_2',
            field=models.ImageField(blank=True, height_field=1000, max_length=1000, null=True, upload_to='play/templates/image/consequence_2', width_field=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_Event',
            field=models.ImageField(blank=True, height_field=1000, max_length=1000, null=True, upload_to='play/templates/image/event', width_field=1000),
        ),
    ]
