# Generated by Django 5.1.4 on 2025-03-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_event_image_consequence_1_event_image_consequence_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='received_medicinal_herbs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Лечебные травы'),
        ),
    ]
