# Generated by Django 5.1.4 on 2025-03-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_event_received_medicinal_herbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lost_HP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='lost_HP_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='lost_Loyalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='lost_Loyalty_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='lost_Money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='lost_Money_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='received_HP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='received_HP_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='received_Loyalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='received_Loyalty_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='received_Money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='received_Money_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='received_medicinal_herbs',
            field=models.IntegerField(default=0, verbose_name='Лечебные травы'),
        ),
    ]
