# Generated by Django 5.1.4 on 2025-03-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_alter_event_lost_hp_alter_event_lost_hp_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='received_medicinal_herbs',
            new_name='received_Medicinal_herbs',
        ),
        migrations.AddField(
            model_name='event',
            name='event_Season',
            field=models.CharField(default='summer', max_length=500, verbose_name='Время года'),
        ),
        migrations.AlterField(
            model_name='event',
            name='action_1',
            field=models.CharField(max_length=500, verbose_name='Действие 1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='action_2',
            field=models.CharField(max_length=500, verbose_name='Действие 2'),
        ),
        migrations.AlterField(
            model_name='event',
            name='consequence_1',
            field=models.CharField(max_length=500, verbose_name='Последствие 1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='consequence_2',
            field=models.CharField(max_length=500, verbose_name='Последствие 2'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_Text',
            field=models.CharField(max_length=500, verbose_name='Текст события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_Consequence_1',
            field=models.ImageField(blank=True, height_field=1000, max_length=1000, null=True, upload_to='play/templates/image/consequence_1', verbose_name='Изображение последствия 1', width_field=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_Consequence_2',
            field=models.ImageField(blank=True, height_field=1000, max_length=1000, null=True, upload_to='play/templates/image/consequence_2', verbose_name='Изображение последствия 2', width_field=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_Event',
            field=models.ImageField(blank=True, height_field=1000, max_length=1000, null=True, upload_to='play/templates/image/event', verbose_name='Изображение события', width_field=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='lost_HP',
            field=models.IntegerField(default=0, verbose_name='Потеряно здоровье 1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lost_HP_2',
            field=models.IntegerField(default=0, verbose_name='Потеряно здоровье 2'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lost_Loyalty',
            field=models.IntegerField(default=0, verbose_name='Потеряно лояльности 1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lost_Loyalty_2',
            field=models.IntegerField(default=0, verbose_name='Потеряно лояльности 2'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lost_Money',
            field=models.IntegerField(default=0, verbose_name='Потеряно монет 1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lost_Money_2',
            field=models.IntegerField(default=0, verbose_name='Потеряно монет 2'),
        ),
        migrations.AlterField(
            model_name='event',
            name='received_HP',
            field=models.IntegerField(default=0, verbose_name='Получено здоровья 1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='received_HP_2',
            field=models.IntegerField(default=0, verbose_name='Получено здоровье 2'),
        ),
        migrations.AlterField(
            model_name='event',
            name='received_Loyalty',
            field=models.IntegerField(default=0, verbose_name='Получено лояльности 1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='received_Loyalty_2',
            field=models.IntegerField(default=0, verbose_name='Получено лояльности 2'),
        ),
        migrations.AlterField(
            model_name='event',
            name='received_Money',
            field=models.IntegerField(default=0, verbose_name='Получено монет 1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='received_Money_2',
            field=models.IntegerField(default=0, verbose_name='Получено монет 2'),
        ),
    ]
