# Generated by Django 5.1.4 on 2025-03-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_rename_received_medicinal_herbs_event_received_medicinal_herbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_Event',
            field=models.ImageField(blank=True, height_field=10000, max_length=10000, null=True, upload_to='play/templates/image/event', verbose_name='Изображение события', width_field=10000),
        ),
    ]
