# Generated by Django 5.1.4 on 2025-04-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0007_alter_event_image_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_Consequence_1',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='play/templates/image/consequence_1', verbose_name='Изображение последствия 1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_Consequence_2',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='play/templates/image/consequence_2', verbose_name='Изображение последствия 2'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_Event',
            field=models.ImageField(blank=True, max_length=10000, null=True, upload_to='image/event', verbose_name='Изображение события'),
        ),
    ]
