# Generated by Django 5.1.4 on 2025-04-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0008_alter_event_image_consequence_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_Consequence_1',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image_Consequence_2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lost_HP',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lost_HP_2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lost_Loyalty',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lost_Loyalty_2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lost_Money',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lost_Money_2',
        ),
        migrations.AlterField(
            model_name='event',
            name='received_HP',
            field=models.IntegerField(default=0, verbose_name='Изменение здоровья 1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='received_HP_2',
            field=models.IntegerField(default=0, verbose_name='Изменение здоровье 2'),
        ),
        migrations.AlterField(
            model_name='event',
            name='received_Loyalty',
            field=models.IntegerField(default=0, verbose_name='Изменение лояльности 1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='received_Loyalty_2',
            field=models.IntegerField(default=0, verbose_name='Изменение лояльности 2'),
        ),
        migrations.AlterField(
            model_name='event',
            name='received_Money',
            field=models.IntegerField(default=0, verbose_name='Изменение монет 1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='received_Money_2',
            field=models.IntegerField(default=0, verbose_name='Изменение монет 2'),
        ),
    ]
