# Generated by Django 5.1.4 on 2025-04-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0009_remove_event_image_consequence_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_HP',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_Loyalty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_Money',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
