# Generated by Django 5.1.4 on 2025-04-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0010_alter_status_status_hp_alter_status_status_loyalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_Herbs',
            field=models.IntegerField(default=0),
        ),
    ]
