# Generated by Django 5.1.4 on 2025-07-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0011_status_status_herbs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'statuses'},
        ),
    ]
