# Generated by Django 5.1.4 on 2025-07-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0012_alter_status_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='received_Samogon',
            field=models.IntegerField(default=0, verbose_name='Самогон'),
        ),
        migrations.AddField(
            model_name='status',
            name='status_Samogon',
            field=models.IntegerField(default=0),
        ),
    ]
