# Generated by Django 5.1.4 on 2025-07-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0013_event_received_samogon_status_status_samogon'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='received_Poison',
            field=models.IntegerField(default=0, verbose_name='Яд'),
        ),
    ]
