# Generated by Django 5.1.4 on 2025-07-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0015_status_status_poison'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='received_Fish',
            field=models.IntegerField(default=0, verbose_name='Рыба'),
        ),
        migrations.AddField(
            model_name='status',
            name='status_Fish',
            field=models.IntegerField(default=0),
        ),
    ]
