# Generated by Django 5.1.4 on 2025-07-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0016_event_received_fish_status_status_fish'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='received_Fish_2',
            field=models.IntegerField(default=0, verbose_name='Рыба'),
        ),
        migrations.AddField(
            model_name='event',
            name='received_Medicinal_herbs_2',
            field=models.IntegerField(default=0, verbose_name='Лечебные травы'),
        ),
        migrations.AddField(
            model_name='event',
            name='received_Poison_2',
            field=models.IntegerField(default=0, verbose_name='Яд'),
        ),
        migrations.AddField(
            model_name='event',
            name='received_Samogon_2',
            field=models.IntegerField(default=0, verbose_name='Самогон'),
        ),
    ]
