# Generated by Django 5.1.4 on 2025-07-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0017_event_received_fish_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='received_Jewelry',
            field=models.IntegerField(default=0, verbose_name='Драгоценности'),
        ),
        migrations.AddField(
            model_name='event',
            name='received_Jewelry_2',
            field=models.IntegerField(default=0, verbose_name='Драгоценности'),
        ),
    ]
