# Generated by Django 5.1.4 on 2025-07-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0018_event_received_jewelry_event_received_jewelry_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_Jewelry',
            field=models.IntegerField(default=0),
        ),
    ]
