# Generated by Django 5.1.4 on 2025-07-31 20:06

import datetime
import django.db.models.deletion
import play.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0019_status_status_jewelry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_HP',
            field=models.IntegerField(blank=True, default=100, null=True, validators=[play.models.validate_max_hp_100]),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_Loyalty',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[play.models.validate_max_Loyalty_100]),
        ),
        migrations.CreateModel(
            name='UserDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(default=datetime.date(1701, 4, 1))),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='play_game_date', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
