# Generated by Django 5.1.4 on 2025-08-06 20:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0023_status_current_date_status_last_event_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='current_date',
        ),
        migrations.RemoveField(
            model_name='status',
            name='last_event_id',
        ),
        migrations.RemoveField(
            model_name='userdate',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='userdate',
            name='last_event_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='game_status', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdate',
            name='current_date',
            field=models.DateField(default=datetime.date(1601, 4, 1)),
        ),
    ]
