# Generated by Django 5.1.4 on 2025-08-06 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0024_remove_status_current_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdate',
            name='id',
        ),
        migrations.AlterField(
            model_name='userdate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='play_game_date', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
