# Generated by Django 5.1.4 on 2025-08-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0025_remove_userdate_id_alter_userdate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdate',
            name='current_background',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdate',
            name='current_season',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
