# Generated by Django 5.1.4 on 2025-08-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0026_userdate_current_background_userdate_current_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdate',
            name='previous_season',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
