# Generated by Django 5.1.4 on 2025-08-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0027_userdate_previous_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdate',
            name='previous_season',
        ),
    ]
