# Generated by Django 5.1.4 on 2025-08-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0028_remove_userdate_previous_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='received_Harvest',
            field=models.IntegerField(default=0, verbose_name='Урожай'),
        ),
        migrations.AddField(
            model_name='event',
            name='received_Harvest_2',
            field=models.IntegerField(default=0, verbose_name='Урожай'),
        ),
        migrations.AddField(
            model_name='status',
            name='status_Harvest',
            field=models.IntegerField(default=0),
        ),
    ]
