# Generated by Django 5.1.4 on 2025-08-12 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0029_event_received_harvest_event_received_harvest_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdate',
            name='death_date',
            field=models.DateField(default=datetime.date(1650, 4, 1)),
        ),
    ]
