# Generated by Django 5.1.4 on 2025-08-12 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0030_userdate_death_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdate',
            name='current_date',
            field=models.DateField(default=datetime.date(1649, 4, 1)),
        ),
    ]
