# Generated by Django 5.1.4 on 2025-08-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0031_alter_userdate_current_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdate',
            name='death_date',
            field=models.DateField(),
        ),
    ]
