# Generated by Django 5.1.4 on 2025-08-12 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0032_alter_userdate_death_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdate',
            name='death_date',
            field=models.DateField(default=datetime.date(1650, 4, 1)),
        ),
    ]
